## BASE
set -g base-index 1
set -g renumber-windows on
set -g detach-on-destroy off
set -g set-clipboard on
set -g default-terminal "screen-256color"
setw -g mode-keys vi
set-option -g mouse on
set-option -g status-position top
set-window-option -g automatic-rename off

## BIND
bind-key a set-window-option synchronize-panes\; display-message "synchronize-panes is now #{?pane_synchronized,on,off}"

## Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

##  Configurações do Tema

# set -g @plugin 'khanghh/tmux-dark-plus-theme'
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256' # ou 'dark256', 'light', 'light256'
# set -g @plugin 'odedlaz/tmux-onedark-theme'
# set -g @plugin 'obergodmar/kanagawa-tmux'

set -g @continuum-restore 'on'
set -g status-right-length 100
set -g status-left-length 100

# Configurações de True color
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -ga terminal-overrides ",xterm-256color:Tc"

run '~/.tmux/plugins/tpm/tpm'

