# --- Core & Performance ---
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -s escape-time 0
set -g base-index 1
setw -g pane-base-index 1
set -g status-position top
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# --- Estética Gemini (Cinza Sólido) ---
set -g status-style 'bg=#1e1e1e,fg=#8e8e8e'
set -g message-style 'bg=#2d2d2d,fg=#ffffff,bold'
set -g pane-border-style 'fg=#1e1e1e'
set -g pane-active-border-style 'fg=#444444'

# --- Status Bar (L/R) ---
# --- Status Bar (L/R) ---
set -g status-left-length 30
set -g status-left '#[fg=#ffffff,bold,bg=#2d2d2d] 󱫋 #S #[bg=#1e1e1e,fg=#2d2d2d] '

set -g status-right-length 100
# Mudei o #[fg=#1DB954] para #[fg=#8e8e8e] para manter o padrão Gemini
set -g status-right '#[fg=#444444]│ #[fg=#8e8e8e] #(playerctl -p spotify metadata --format "{{ artist }} - {{ title }}" 2>/dev/null || echo "Offline") #[fg=#444444]│ #[fg=#8e8e8e]󱑎 %H:%M '

# --- Window Styling ---
setw -g window-status-style 'fg=#666666,bg=#1e1e1e'
setw -g window-status-format ' #I:#W '
setw -g window-status-current-style 'fg=#ffffff,bold,bg=#2d2d2d'
setw -g window-status-current-format ' #I:#W '

# --- Plugins (TPM) ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# --- continuum ---
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

run '~/.tmux/plugins/tpm/tpm'
